# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-12-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('cote', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Auteur',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='CoteAuteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Cote auteur',
            },
        ),
        migrations.CreateModel(
            name='CotePrefixe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cote prefixe',
            },
        ),
        migrations.CreateModel(
            name='DirecteurCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Directeur de collection',
            },
        ),
        migrations.CreateModel(
            name='DirecteurPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Directeur de publication',
            },
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Editeur',
            },
        ),
        migrations.CreateModel(
            name='Fonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Fonds',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='LangueOrigine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': "Langue d'origine",
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Localisation',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_1re_publication', models.IntegerField(blank=True, null=True)),
                ('annee_enregistrement', models.IntegerField(blank=True, null=True)),
                ('annee_production', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('cote_annee', models.CharField(blank=True, max_length=100, null=True)),
                ('cote_calcul', models.CharField(blank=True, max_length=100, null=True)),
                ('cote_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('cote_calcul_url', models.CharField(blank=True, max_length=50, null=True)),
                ('protection_droit_auteur', models.NullBooleanField(db_column='Protection_droit_auteur', default=None)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('date_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ajout', models.DateField(auto_now=True, null=True)),
                ('depouillement', models.TextField(blank=True, null=True)),
                ('en_collection', models.TextField(blank=True, null=True)),
                ('instrumentation', models.TextField(blank=True, null=True)),
                ('interprete', models.CharField(blank=True, max_length=200, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('lieu_conservation', models.CharField(blank=True, max_length=200, verbose_name='Lieu de conservation')),
                ('lien', models.URLField(blank=True, verbose_name="Lien vers l'article")),
                ('nb_exemplaire', models.IntegerField(blank=True, null=True)),
                ('nb_page', models.CharField(blank=True, max_length=20)),
                ('nb_volume', models.CharField(blank=True, max_length=20)),
                ('no_page', models.CharField(blank=True, max_length=20)),
                ('no_volume', models.CharField(blank=True, max_length=20)),
                ('notice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('sujet', models.TextField(blank=True, null=True)),
                ('titre', models.CharField(max_length=600)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='.')),
                ('pdf_text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Affiche', 'Affiche'), ('Annonce de concours', 'Annonce de concours'), ('Article de p\xe9riodique', 'Article de p\xe9riodique'), ('Catalogue', 'Catalogue'), ('Conf\xe9rence', 'Conf\xe9rence'), ('Document non publi\xe9', 'Document non publi\xe9'), ('Extrait de livre', 'Extrait de livre'), ('Iconographie', 'Iconographie'), ('Livre', 'Livre'), ('Mat\xe9riel audiovisuel', 'Mat\xe9riel audiovisuel'), ('Partition', 'Partition'), ('P\xe9riodique', 'P\xe9riodique'), ('Photographie', 'Photographie'), ('Programme', 'Programme'), ('R\xe9f\xe9rence', 'R\xe9f\xe9rence')], max_length=100, verbose_name='Type')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Auteur')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Collection')),
                ('cote_auteur', models.ManyToManyField(blank=True, default=None, related_name='Cote_Auteur', to='lmhsweb.Auteur')),
                ('cote_prefixe', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.CotePrefixe')),
                ('directeur_collection', models.ManyToManyField(blank=True, to='lmhsweb.DirecteurCollection')),
                ('directeur_publication', models.ManyToManyField(blank=True, to='lmhsweb.DirecteurPublication')),
                ('editeur', models.ManyToManyField(blank=True, to='lmhsweb.Editeur', verbose_name='\xc9diteur')),
                ('fonds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Fonds', verbose_name='Fonds')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Genre', verbose_name='Genre')),
                ('langue_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.LangueOrigine')),
                ('localisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Localisation')),
            ],
            options={
                'verbose_name': 'Principale',
            },
        ),
        migrations.CreateModel(
            name='MaisonEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': "Maison d'\xe9dition",
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Medium',
            },
        ),
        migrations.CreateModel(
            name='MethodeReproduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'M\xe9thode de r\xe9production',
            },
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Mot cl\xe9',
            },
        ),
        migrations.CreateModel(
            name='NomOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': "Nom de l'organisme",
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Projet',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Support',
            },
        ),
        migrations.CreateModel(
            name='Traducteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Traducteur',
            },
        ),
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': "Type d'\xe9v\xe9nement",
            },
        ),
        migrations.AddField(
            model_name='main',
            name='maison_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.MaisonEdition'),
        ),
        migrations.AddField(
            model_name='main',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Medium'),
        ),
        migrations.AddField(
            model_name='main',
            name='methode_reproduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.MethodeReproduction'),
        ),
        migrations.AddField(
            model_name='main',
            name='mot_cle',
            field=models.ManyToManyField(blank=True, to='lmhsweb.MotCle'),
        ),
        migrations.AddField(
            model_name='main',
            name='nom_org',
            field=models.ManyToManyField(blank=True, to='lmhsweb.NomOrg'),
        ),
        migrations.AddField(
            model_name='main',
            name='projet',
            field=models.ManyToManyField(blank=True, to='lmhsweb.Projet'),
        ),
        migrations.AddField(
            model_name='main',
            name='support',
            field=models.ManyToManyField(blank=True, to='lmhsweb.Support'),
        ),
        migrations.AddField(
            model_name='main',
            name='traducteur',
            field=models.ManyToManyField(blank=True, to='lmhsweb.Traducteur'),
        ),
        migrations.AddField(
            model_name='main',
            name='type_evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.TypeEvenement'),
        ),
    ]
