# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0002_auto_20181222_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='auteur',
            field=models.ManyToManyField(blank=True, to='lmhsweb.Auteur', verbose_name='Auteur(s)'),
        ),
        migrations.AlterField(
            model_name='main',
            name='cote_calcul_url',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='cote_prefixe',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.CotePrefixe'),
        ),
        migrations.AlterField(
            model_name='main',
            name='notice_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
