# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0002_auto_20160617_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la ville')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du pays')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Fonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Fonds',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='LangueOrigine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': "Langue d'origine",
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=200, verbose_name='Lieu')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Country')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieu',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la province')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.AlterField(
            model_name='main',
            name='fonds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Fonds'),
        ),
        migrations.AlterField(
            model_name='main',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Genre'),
        ),
        migrations.AlterField(
            model_name='main',
            name='langue_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.LangueOrigine'),
        ),
        migrations.AlterField(
            model_name='main',
            name='lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.State'),
        ),
    ]
