# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0003_auto_20190702_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='pdf_prive',
            field=models.BooleanField(default=False, verbose_name='Le pdf est seulement accessible aux utilisateurs connect\xe9s'),
        ),
    ]
