# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0003_auto_20160617_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalSupportListMoinsEnligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Support',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Localisation',
            },
        ),
        migrations.CreateModel(
            name='MaisonEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': "Maison d'\xe9dition",
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Medium',
            },
        ),
        migrations.CreateModel(
            name='MethodeReproduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'M\xe9thode de r\xe9production',
            },
        ),
        migrations.CreateModel(
            name='NomOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': "Nom de l'organisme",
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Projet',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Type',
            },
        ),
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': "Type d'\xe9v\xe9nement",
            },
        ),
        migrations.AlterField(
            model_name='main',
            name='annee_1re_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='annee_enregistrement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='annee_production',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='cal_support_list_moins_enligne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.CalSupportListMoinsEnligne'),
        ),
        migrations.AlterField(
            model_name='main',
            name='cote_annee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='lieu_conservation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='localisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Localisation'),
        ),
        migrations.AlterField(
            model_name='main',
            name='maison_edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.MaisonEdition'),
        ),
        migrations.AlterField(
            model_name='main',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Medium'),
        ),
        migrations.AlterField(
            model_name='main',
            name='methode_reproduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.MethodeReproduction'),
        ),
        migrations.AlterField(
            model_name='main',
            name='nom_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.NomOrg'),
        ),
        migrations.AlterField(
            model_name='main',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Projet'),
        ),
        migrations.AlterField(
            model_name='main',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Type'),
        ),
        migrations.AlterField(
            model_name='main',
            name='type_evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.TypeEvenement'),
        ),
    ]
