# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-13 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0004_main_pdf_prive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='pdf_prive',
        ),
        migrations.AddField(
            model_name='main',
            name='pdf_file_prive',
            field=models.FileField(blank=True, null=True, upload_to='/prive/documents'),
        ),
        migrations.AlterField(
            model_name='main',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='/public/documents'),
        ),
    ]
