# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0004_auto_20160617_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='cote_calcul',
        ),
        migrations.RemoveField(
            model_name='main',
            name='cote_calcul_url',
        ),
        migrations.RemoveField(
            model_name='main',
            name='cote_per_calcul',
        ),
        migrations.RemoveField(
            model_name='main',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='main',
            name='id_org',
        ),
        migrations.RemoveField(
            model_name='main',
            name='notice_id',
        ),
        migrations.RemoveField(
            model_name='main',
            name='organisme',
        ),
        migrations.RemoveField(
            model_name='main',
            name='source_per',
        ),
        migrations.RemoveField(
            model_name='main',
            name='source_per_calcul',
        ),
    ]
