# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0005_auto_20160617_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='auteur_old',
        ),
        migrations.RemoveField(
            model_name='main',
            name='cote_auteur',
        ),
        migrations.RemoveField(
            model_name='main',
            name='tousindex_calcul',
        ),
        migrations.AlterField(
            model_name='main',
            name='depouillement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='instrumentation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='interprete',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='sujet',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='support',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
