# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0006_auto_20160617_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirecteurCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Directeur de collection',
            },
        ),
        migrations.CreateModel(
            name='DirecteurPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Directeur de publication',
            },
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Editeur',
            },
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Mot cl\xe9',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Support',
            },
        ),
        migrations.CreateModel(
            name='Traducteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Traducteur',
            },
        ),
        migrations.RemoveField(
            model_name='main',
            name='directeur_collection',
        ),
        migrations.RemoveField(
            model_name='main',
            name='directeur_publication',
        ),
        migrations.RemoveField(
            model_name='main',
            name='editeur',
        ),
        migrations.RemoveField(
            model_name='main',
            name='mot_cle',
        ),
        migrations.RemoveField(
            model_name='main',
            name='support',
        ),
        migrations.RemoveField(
            model_name='main',
            name='traducteur',
        ),
        migrations.AddField(
            model_name='main',
            name='directeur_collection',
            field=models.ManyToManyField(to='lmhsweb.DirecteurCollection'),
        ),
        migrations.AddField(
            model_name='main',
            name='directeur_publication',
            field=models.ManyToManyField(to='lmhsweb.DirecteurPublication'),
        ),
        migrations.AddField(
            model_name='main',
            name='editeur',
            field=models.ManyToManyField(to='lmhsweb.Editeur'),
        ),
        migrations.AddField(
            model_name='main',
            name='mot_cle',
            field=models.ManyToManyField(to='lmhsweb.MotCle'),
        ),
        migrations.AddField(
            model_name='main',
            name='support',
            field=models.ManyToManyField(to='lmhsweb.Support'),
        ),
        migrations.AddField(
            model_name='main',
            name='traducteur',
            field=models.ManyToManyField(to='lmhsweb.Traducteur'),
        ),
    ]
