# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-15 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0007_auto_20190813_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='main',
            name='pdf_public',
            field=models.FileField(blank=True, null=True, upload_to='public/documents'),
        ),
    ]
