# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0007_auto_20160617_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='cal_support_enligne',
        ),
        migrations.RemoveField(
            model_name='main',
            name='cal_support_list_moins_enligne',
        ),
        migrations.AlterField(
            model_name='main',
            name='commentaire',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='CalSupportListMoinsEnligne',
        ),
    ]
