# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-15 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0008_auto_20190815_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='pdf_prive',
            field=models.FileField(blank=True, null=True, upload_to='prive/documents'),
        ),
    ]
