# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0009_auto_20190815_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='pdf_public',
            new_name='pdf_file',
        ),
        migrations.AlterField(
            model_name='main',
            name='pdf_prive',
            field=models.BooleanField(default=False, verbose_name='PDF seulement accessible aux utilisateurs connect\xe9s'),
        ),
    ]
