# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0009_auto_20160617_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='type',
            field=models.CharField(choices=[('Affiche', 'Affiche'), ('Annonce de concours', 'Annonce de concours'), ('Article de p\xe9riodique', 'Article de p\xe9riodique'), ('Catalogue', 'Catalogue'), ('Conf\xe9rence', 'Conf\xe9rence'), ('Document non publi\xe9', 'Document non publi\xe9'), ('Extrait de livre', 'Extrait de livre'), ('Iconographie', 'Iconographie'), ('Livre', 'Livre'), ('Mat\xe9riel audiovisuel', 'Mat\xe9riel audiovisuel'), ('Partition', 'Partition'), ('P\xe9riodique', 'P\xe9riodique'), ('Photographie', 'Photographie'), ('Programme', 'Programme'), ('R\xe9f\xe9rence', 'R\xe9f\xe9rence')], default='', max_length=100, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
