# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0010_auto_20160623_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='state',
        ),
        migrations.AddField(
            model_name='main',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.City'),
        ),
        migrations.AddField(
            model_name='main',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Country'),
        ),
        migrations.AddField(
            model_name='main',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.State'),
        ),
        migrations.AlterField(
            model_name='main',
            name='lieu',
            field=models.CharField(default='', max_length=200, verbose_name='Lieu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main',
            name='lieu_conservation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu de conservation'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
