# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-18 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0010_auto_20190815_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=400)),
                ('statut', models.CharField(max_length=400)),
                ('courriel', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('raison', models.TextField()),
            ],
        ),
    ]
