# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-19 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0011_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2019, 8, 19, 16, 0, 30, 620450, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
