# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0011_auto_20160623_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoteAuteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Cote auteur',
            },
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='cote',
        ),
        migrations.AlterField(
            model_name='auteur',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom de la ville'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='nom',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom du pays'),
        ),
        migrations.AlterField(
            model_name='directeurcollection',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='directeurpublication',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='editeur',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fonds',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='langueorigine',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='maisonedition',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='methodereproduction',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='motcle',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nomorg',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom de la province'),
        ),
        migrations.AlterField(
            model_name='support',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='traducteur',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='typeevenement',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='main',
            name='cote_auteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.CoteAuteur'),
            preserve_default=False,
        ),
    ]
