# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0012_utilisateur_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='etat',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
