# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0013_auto_20160625_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='cote_annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='protection_droit_auteur',
            field=models.NullBooleanField(db_column='Protection_droit_auteur', default=None),
        ),
    ]
