# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0015_auto_20160627_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coteauteur',
            name='cote',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main',
            name='cote_auteur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.CoteAuteur'),
        ),
    ]
