# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0016_auto_20160627_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coteauteur',
            name='cote',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
