# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0017_auto_20160627_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='cote_calcul',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='cote_calcul_url',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='notice_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
