# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0018_auto_20160627_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='cote_calcul',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='cote_calcul_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='cote_prefixe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
