# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0023_auto_20160710_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coteauteur',
            name='cote',
            field=models.CharField(blank=True, default='', max_length=200, null=True, unique=True),
        ),
    ]
