# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0028_auto_20160714_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='notice',
        ),
        migrations.AddField(
            model_name='main',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='PDF'),
        ),
        migrations.AddField(
            model_name='main',
            name='pdf_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
