# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0029_auto_20160714_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
