# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0028_auto_20160710_1816'),
        ('lmhsweb', '0030_auto_20160714_2102'),
    ]

    operations = [
    ]
