# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0031_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='en_collection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
