# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0032_auto_20160718_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='nom_org',
        ),
        migrations.AddField(
            model_name='main',
            name='nom_org',
            field=models.ManyToManyField(blank=True, null=True, to='lmhsweb.NomOrg'),
        ),
    ]
