# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0033_auto_20160718_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='.'),
        ),
    ]
