# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0034_auto_20160810_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='projet',
        ),
        migrations.AddField(
            model_name='main',
            name='projet',
            field=models.ManyToManyField(blank=True, null=True, to='lmhsweb.Projet'),
        ),
    ]
