# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0039_auto_20161025_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodereproduction',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
