# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0043_auto_20161025_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coteauteur',
            name='auteur',
        ),
        migrations.AddField(
            model_name='auteur',
            name='cote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.CoteAuteur'),
        ),
    ]
