# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0044_auto_20161026_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='cote',
        ),
    ]
