# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0045_remove_auteur_cote'),
    ]

    operations = [
        migrations.AddField(
            model_name='coteauteur',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Auteur'),
        ),
    ]
