# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0047_auto_20161026_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='cote',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
