# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0048_auto_20161026_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='cote_auteur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoteAuteur', to='lmhsweb.Auteur'),
        ),
    ]
