# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-23 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0049_auto_20161026_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='date_ajout',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='lien',
            field=models.URLField(blank=True, verbose_name="Lien vers l'article"),
        ),
        migrations.AddField(
            model_name='main',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmhsweb.Auteur'),
        ),
        migrations.AlterField(
            model_name='main',
            name='cote_calcul_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='directeur_collection',
            field=models.ManyToManyField(blank=True, to='lmhsweb.DirecteurCollection'),
        ),
        migrations.AlterField(
            model_name='main',
            name='directeur_publication',
            field=models.ManyToManyField(blank=True, to='lmhsweb.DirecteurPublication'),
        ),
        migrations.AlterField(
            model_name='main',
            name='editeur',
            field=models.ManyToManyField(blank=True, to='lmhsweb.Editeur', verbose_name='\xc9diteur'),
        ),
        migrations.AlterField(
            model_name='main',
            name='mot_cle',
            field=models.ManyToManyField(blank=True, to='lmhsweb.MotCle'),
        ),
        migrations.AlterField(
            model_name='main',
            name='nom_org',
            field=models.ManyToManyField(blank=True, to='lmhsweb.NomOrg'),
        ),
        migrations.AlterField(
            model_name='main',
            name='projet',
            field=models.ManyToManyField(blank=True, to='lmhsweb.Projet'),
        ),
        migrations.AlterField(
            model_name='main',
            name='support',
            field=models.ManyToManyField(blank=True, to='lmhsweb.Support'),
        ),
        migrations.AlterField(
            model_name='main',
            name='titre',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='main',
            name='traducteur',
            field=models.ManyToManyField(blank=True, to='lmhsweb.Traducteur'),
        ),
    ]
