# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0050_auto_20181022_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.RemoveField(
            model_name='main',
            name='cote_auteur',
        ),
        migrations.AddField(
            model_name='main',
            name='cote_auteur',
            field=models.ManyToManyField(blank=True, default=None, related_name='Cote_Auteur', to='lmhsweb.Auteur'),
        ),
    ]
