# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0051_source'),
    ]

    operations = [
 
    ]
