# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0052_auto_20170801_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
