# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0053_auto_20170801_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='titre',
            field=models.CharField(max_length=600),
        ),
    ]
