# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0054_auto_20170920_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='sourceU',
            field=models.ManyToManyField(blank=True, null=True, to='lmhsweb.Source'),
        ),
    ]
