# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-08 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhsweb', '0055_main_sourceu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='sourceU',
        ),
        migrations.AlterField(
            model_name='main',
            name='cote_calcul_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
